package dev.klipper.configurator.core

import java.io.ByteArrayInputStream
import java.io.ByteArrayOutputStream
import java.security.MessageDigest
import java.time.Instant
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream

enum class Severity { ERROR, WARNING, INFO }
data class ValidationIssue(val severity: Severity, val field: String, val message: String)
data class GeneratedBundle(val files: Map<String, ByteArray>, val issues: List<ValidationIssue>)

object ConfigGenerator {
    fun validate(p: ConfigProject): List<ValidationIssue> = buildList {
        if (p.name.isBlank()) add(ValidationIssue(Severity.ERROR, "name", "Printer name is required"))
        if (p.bedWidth !in 50..1000 || p.bedDepth !in 50..1000 || p.buildHeight !in 50..1500)
            add(ValidationIssue(Severity.ERROR, "volume", "Build dimensions are outside supported limits"))
        if (p.zMotorCount !in 1..4) add(ValidationIssue(Severity.ERROR, "zMotorCount", "Z motor count must be 1 through 4"))
        if (p.mcuSerial.isBlank() || p.mcuSerial.endsWith("CHANGE_ME")) add(ValidationIssue(Severity.WARNING, "mcuSerial", "Set the deployed MCU serial path before starting Klipper"))
        val board = ConfigCatalog.controllers.firstOrNull { it.id == p.controllerId }
        val effectivePins = (board?.pins ?: emptyMap()) + p.pinOverrides
        val requiredPins = setOf("x_step", "x_dir", "x_enable", "x_endstop", "y_step", "y_dir", "y_enable", "y_endstop", "z_step", "z_dir", "z_enable", "z_endstop", "e_step", "e_dir", "e_enable", "heater_bed", "heater_hotend", "sensor_bed", "sensor_hotend", "fan_part", "fan_hotend")
        val missingPins = requiredPins - effectivePins.keys
        if (missingPins.isNotEmpty()) add(ValidationIssue(Severity.WARNING, "controller", "Manual pin mapping is incomplete: ${missingPins.sorted().joinToString() }"))
        val duplicates = effectivePins.filterKeys { it in requiredPins }.entries.groupBy { it.value.trimStart('!', '^', '~') }.filterValues { it.size > 1 }
        if (duplicates.isNotEmpty()) add(ValidationIssue(Severity.ERROR, "pins", "Pins assigned more than once: ${duplicates.keys.sorted().joinToString()}"))
        if (p.controllerId == "btt-skr-mini-e3-v3" && listOf(p.xyDriver, p.zDriver, p.extruderDriver).any { it != DriverKind.TMC2209 })
            add(ValidationIssue(Severity.WARNING, "drivers", "SKR Mini E3 V3 has integrated TMC2209 drivers; selected overrides require different hardware"))
        if (p.zMotorCount > 1) add(ValidationIssue(Severity.WARNING, "zMotorCount", "Complete additional Z motor pin assignments in the exported config"))
        if (p.probe in setOf(ProbeKind.BEACON, ProbeKind.CARTOGRAPHER)) add(ValidationIssue(Severity.WARNING, "probe", "Install and verify the probe extension before activating its config"))
        if (p.maxVelocity !in 1..1000 || p.maxAccel !in 1..50000) add(ValidationIssue(Severity.ERROR, "motion", "Motion limits are outside supported bounds"))
        if (p.hotendMaxTemp !in 100..500 || p.bedMaxTemp !in 40..200) add(ValidationIssue(Severity.ERROR, "thermal", "Temperature limits are outside supported bounds"))
        if (p.kinematics == Kinematics.DELTA) add(ValidationIssue(Severity.WARNING, "kinematics", "Delta tower geometry requires manual completion in the generated motion config"))
    }

    fun generate(p: ConfigProject): GeneratedBundle {
        val issues = validate(p)
        val boardBase = ConfigCatalog.controllers.firstOrNull { it.id == p.controllerId } ?: ConfigCatalog.controllers.first()
        val board = boardBase.copy(pins = boardBase.pins + p.pinOverrides)
        val files = linkedMapOf<String, String>()
        files["printer.cfg"] = "# Generated by Klipper Configurator. Review validation-report.txt before use.\n[include k4a/current.cfg]\n"
        files["k4a/current.cfg"] = "# Active generated revision.\n[include k4a/revisions/generated/*.cfg]\n"
        files["k4a/revisions/generated/10-mcu.cfg"] = "[mcu]\nserial: ${p.mcuSerial}\nrestart_method: command\n"
        files["k4a/revisions/generated/20-motion.cfg"] = motion(p, board)
        files["k4a/revisions/generated/30-thermal.cfg"] = thermal(p, board)
        files["k4a/revisions/generated/40-probe.cfg"] = probe(p, board)
        files["k4a/revisions/generated/50-features.cfg"] = features(p)
        files["README.txt"] = readme(p)
        files["firmware/BUILD_SETTINGS.txt"] = firmware(p, board)
        files["validation-report.txt"] = if (issues.isEmpty()) "No model validation issues. Physical commissioning is still required.\n" else issues.joinToString("\n", postfix = "\n") { "${it.severity}: ${it.field}: ${it.message}" }
        files["klipper-config-project.properties"] = ProjectCodec.encode(p).decodeToString()
        val hashes = files.mapValues { sha256(it.value.encodeToByteArray()) }
        files["manifest.properties"] = buildString {
            appendLine("schemaVersion=${p.schemaVersion}"); appendLine("generator=Klipper Configurator")
            appendLine("generatedAt=${Instant.now()}"); appendLine("target=${p.target.name}")
            hashes.forEach { (path, hash) -> appendLine("sha256.${path.replace('=', '_')}=$hash") }
        }
        return GeneratedBundle(files.mapValues { it.value.encodeToByteArray() }, issues)
    }

    fun zip(bundle: GeneratedBundle): ByteArray = ByteArrayOutputStream().also { out ->
        ZipOutputStream(out).use { zip -> bundle.files.toSortedMap().forEach { (path, bytes) ->
            zip.putNextEntry(ZipEntry(path)); zip.write(bytes); zip.closeEntry()
        } }
    }.toByteArray()

    fun importProject(bytes: ByteArray): ConfigProject {
        ZipInputStream(ByteArrayInputStream(bytes)).use { zip -> while (true) {
            val entry = zip.nextEntry ?: break
            require(!entry.name.startsWith("/") && !entry.name.split('/').contains("..")) { "Unsafe ZIP path" }
            if (entry.name == "klipper-config-project.properties") return ProjectCodec.decode(zip.readBytes())
        } }
        error("This ZIP does not contain an editable Klipper Configurator project")
    }

    private fun motion(p: ConfigProject, b: ControllerBoard): String {
        fun pin(k: String) = p.pinOverrides[k] ?: b.pins[k] ?: "CHANGE_ME_${k.uppercase()}"
        fun stepper(axis: String, driver: DriverKind, rotation: Double, max: Int) = buildString {
            appendLine("[stepper_$axis]"); appendLine("step_pin: ${pin("${axis}_step")}"); appendLine("dir_pin: ${pin("${axis}_dir")}")
            appendLine("enable_pin: ${pin("${axis}_enable")}"); appendLine("microsteps: 16"); appendLine("rotation_distance: $rotation")
            appendLine("endstop_pin: ${pin("${axis}_endstop")}"); appendLine("position_endstop: 0"); appendLine("position_max: $max")
            appendLine("homing_speed: ${if (axis == "z") 8 else 50}")
            val current = if (axis == "z") p.zRunCurrent else p.xyRunCurrent
            driver(driver, "stepper_$axis", b, b.uartAddresses[axis], current)?.let { appendLine(); append(it) }
        }
        return buildString {
            append(stepper("x", p.xyDriver, p.xyRotationDistance, p.bedWidth)); appendLine(); append(stepper("y", p.xyDriver, p.xyRotationDistance, p.bedDepth)); appendLine()
            append(stepper("z", p.zDriver, p.zRotationDistance, p.buildHeight)); appendLine(); appendLine("[printer]"); appendLine("kinematics: ${p.kinematics.configValue}")
            appendLine("max_velocity: ${p.maxVelocity}"); appendLine("max_accel: ${p.maxAccel}"); appendLine("max_z_velocity: 15"); appendLine("max_z_accel: 100"); appendLine("square_corner_velocity: 5")
        }
    }

    private fun driver(kind: DriverKind, stepper: String, b: ControllerBoard, address: Int?, current: Double): String? = kind.section?.let { section -> buildString {
        appendLine("[$section $stepper]")
        if (kind == DriverKind.TMC2209) { appendLine("uart_pin: ${b.pins["uart"] ?: "CHANGE_ME_UART_PIN"}"); address?.let { appendLine("uart_address: $it") } }
        else appendLine("cs_pin: CHANGE_ME_CS_PIN")
        appendLine("run_current: $current"); appendLine("stealthchop_threshold: 0")
    } }

    private fun thermal(p: ConfigProject, b: ControllerBoard): String {
        fun pin(k: String) = p.pinOverrides[k] ?: b.pins[k] ?: "CHANGE_ME_${k.uppercase()}"
        return """[extruder]
step_pin: ${pin("e_step")}
dir_pin: ${pin("e_dir")}
enable_pin: ${pin("e_enable")}
microsteps: 16
rotation_distance: ${p.extruderRotationDistance}
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: ${pin("heater_hotend")}
sensor_type: ${p.hotendSensor}
sensor_pin: ${pin("sensor_hotend")}
control: pid
pid_Kp: 20.0
pid_Ki: 1.0
pid_Kd: 100.0
min_temp: 0
max_temp: ${p.hotendMaxTemp}

[heater_bed]
heater_pin: ${pin("heater_bed")}
sensor_type: ${p.bedSensor}
sensor_pin: ${pin("sensor_bed")}
control: watermark
min_temp: 0
max_temp: ${p.bedMaxTemp}

[fan]
pin: ${pin("fan_part")}

[heater_fan hotend_fan]
pin: ${pin("fan_hotend")}
heater: extruder
heater_temp: 50.0
""" + (driver(p.extruderDriver, "extruder", b, b.uartAddresses["extruder"], p.extruderRunCurrent)?.let { "\n$it" } ?: "")
    }

    private fun probe(p: ConfigProject, b: ControllerBoard): String {
        val pin = p.pinOverrides["probe"] ?: b.pins["probe"] ?: "CHANGE_ME_PROBE_PIN"; val servo = p.pinOverrides["servo"] ?: b.pins["servo"] ?: "CHANGE_ME_SERVO_PIN"
        val section = when (p.probe) {
            ProbeKind.NONE -> "# No probe selected; Z uses its physical endstop.\n"
            ProbeKind.BLTOUCH -> "[bltouch]\nsensor_pin: $pin\ncontrol_pin: $servo\nx_offset: ${p.probeXOffset}\ny_offset: ${p.probeYOffset}\nz_offset: ${p.probeZOffset}\n"
            ProbeKind.BTT_EDDY -> "# Complete MCU/I2C values from the BTT guide.\n[probe_eddy_current btt_eddy]\nsensor_type: ldc1612\ni2c_mcu: eddy\ni2c_bus: i2c0f\nx_offset: 0\ny_offset: 0\nz_offset: 2.5\n"
            ProbeKind.BEACON -> "# Beacon draft: install Beacon, then add its verified [beacon] settings.\n"
            ProbeKind.CARTOGRAPHER -> "# Cartographer draft: install Cartographer, then add verified settings.\n"
            else -> "[probe]\npin: $pin\nx_offset: ${p.probeXOffset}\ny_offset: ${p.probeYOffset}\nz_offset: ${p.probeZOffset}\nspeed: 5\nsamples: 2\n"
        }
        return section + if (!p.bedMesh) "" else "\n[bed_mesh]\nspeed: 100\nhorizontal_move_z: 5\nmesh_min: 20, 20\nmesh_max: ${p.bedWidth - 20}, ${p.bedDepth - 20}\nprobe_count: 5, 5\nadaptive_margin: ${if (p.adaptiveMesh) 5 else 0}\n"
    }

    private fun features(p: ConfigProject) = buildString {
        appendLine("[virtual_sdcard]"); appendLine("path: ${if (p.target == DeploymentTarget.K4A_TERMUX) "/data/data/com.termux/files/home/printer_data/gcodes" else "~/printer_data/gcodes"}")
        appendLine(); appendLine("[pause_resume]"); appendLine(); appendLine("[display_status]"); appendLine(); appendLine("[respond]"); appendLine(); appendLine("[exclude_object]")
        if (p.inputShaper) { appendLine(); appendLine("[input_shaper]"); appendLine("shaper_freq_x: 0"); appendLine("shaper_freq_y: 0") }
        if (p.filamentSensor) { appendLine(); appendLine("[filament_switch_sensor runout]"); appendLine("switch_pin: CHANGE_ME_FILAMENT_SENSOR_PIN"); appendLine("pause_on_runout: True") }
    }

    private fun firmware(p: ConfigProject, b: ControllerBoard) = "Printer: ${p.name}\nController: ${b.name} ${b.exactRevision}\n\nBuild and flash Klipper using the board manufacturer's exact revision guide. This app does not flash firmware.\nExpected MCU path: ${p.mcuSerial}\n"
    private fun readme(p: ConfigProject) = "KLIPPER CONFIG BUNDLE — ${p.name}\n\nTarget: ${p.target.label}\n\n1. Resolve validation-report.txt.\n2. Back up printer_data/config.\n3. Copy printer.cfg and k4a into that directory.\n4. Verify MCU, pins, sensors, heaters, motors, and endstops.\n5. Restart Klipper; do not move or heat until configuration checks pass.\n\nReopen this ZIP in Klipper Configurator to continue editing.\n"
    private fun sha256(bytes: ByteArray) = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }
}
