[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: @DATA_DIR@/comms/klippy.sock

[file_manager]
config_path: @DATA_DIR@/config
log_path: @DATA_DIR@/logs

[authorization]
trusted_clients:
    127.0.0.0/8
    10.0.0.0/8
    172.16.0.0/12
    192.168.0.0/16

