daemon off;
worker_processes 1;
error_log @DATA_DIR@/logs/nginx-error.log;
pid @DATA_DIR@/nginx.pid;

events { worker_connections 128; }
http {
    include @PREFIX@/etc/nginx/mime.types;
    access_log @DATA_DIR@/logs/nginx-access.log;
    server {
        listen @WEB_PORT@;
        server_name _;
        root @HOME@/mainsail;
        index index.html;
        location = /firmware { return 301 /firmware/; }
        location /firmware/ {
            alias @DATA_DIR@/gcodes/firmware/;
            index index.html;
            autoindex off;
            default_type application/octet-stream;
            add_header X-Content-Type-Options nosniff always;
        }
        location / { try_files $uri $uri/ /index.html; }
        location /websocket {
            proxy_pass http://127.0.0.1:7125/websocket;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
        location ~ ^/(printer|api|access|machine|server)/ {
            proxy_pass http://127.0.0.1:7125$request_uri;
            proxy_set_header Host $http_host;
        }
    }
}
